-- ============================================================
-- Question 1
-- Business Problem:
-- Find the total revenue generated by each product category.
-- ============================================================

select
p.product_category_name,
sum(oi.price) as revenue
from products p
join order_items oi
on p.product_id = oi.product_id
group by p.product_category_name
order by revenue desc;



-- ============================================================
-- Question 2
-- Business Problem:
-- Find one-time customers and repeat customers.
-- ============================================================

select
customer_type,
count(*) as total_customers
from
(
select
c.customer_unique_id,
case
    when count(distinct o.order_id) = 1 then 'One-Time Customer'
    else 'Repeat Customer'
end as customer_type
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_unique_id
)t1
group by customer_type;



-- ============================================================
-- Question 3
-- Business Problem:
-- Find the top 10 customers by total revenue.
-- ============================================================

select
c.customer_unique_id,
sum(oi.price) as revenue
from customers c
join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
group by c.customer_unique_id
order by revenue desc
limit 10;



-- ============================================================
-- Question 4
-- Business Problem:
-- Rank product categories based on total revenue.
-- ============================================================

select
product_category_name,
revenue,
dense_rank() over(order by revenue desc) as category_rank
from
(
select
p.product_category_name,
sum(oi.price) as revenue
from products p
join order_items oi
on p.product_id = oi.product_id
group by p.product_category_name
)t1;



-- ============================================================
-- Question 5
-- Business Problem:
-- Find monthly revenue trend.
-- ============================================================

select
date_trunc('month',o.order_purchase_timestamp) as month,
sum(oi.price) as revenue
from orders o
join order_items oi
on o.order_id = oi.order_id
group by month
order by month;