-- ==========================================
-- Question 1
-- Business Problem:
-- Find the total number of customers.
-- ==========================================

select
count(distinct customer_unique_id) as total_customers
from customers;



-- ==========================================
-- Question 2
-- Business Problem:
-- Find total orders placed by customers.
-- ==========================================

select
count(distinct order_id) as total_orders
from orders;



-- ==========================================
-- Question 3
-- Business Problem:
-- Calculate total revenue generated.
-- ==========================================


select
sum(price) as total_revenue
from order_items;


-- ==========================================
-- Question 4
-- Business Problem:
-- Find revenue generated by each state.
-- ==========================================

select
c.customer_state,
sum(oi.price) as revenue
from customers c
join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
group by c.customer_state
order by revenue desc;



-- ==========================================
-- Question 5
-- Business Problem:
-- Find total orders placed in each state.
-- ==========================================

select
c.customer_state,
count(distinct o.order_id) as total_orders
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_state
order by total_orders desc;




